/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaoxiukj_jhan_androidtest_OpenCVHelper */

#ifndef _Included_com_xiaoxiukj_jhan_androidtest_OpenCVHelper
#define _Included_com_xiaoxiukj_jhan_androidtest_OpenCVHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaoxiukj_jhan_androidtest_OpenCVHelper
 * Method:    gray
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_xiaoxiukj_jhan_androidtest_OpenCVHelper_gray
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
